configName: ili9488_rgb565_c21
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAMC21J18A
projectName: ''
settings:
  PackageFilter: gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx;bsp;usb;gfx;csp;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;core;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: ./dev_packs/arm/CMSIS/5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: ./dev_packs/Microchip/SAMC21_DFP/3.5.83/samc21/atdf/ATSAMC21J18A.atdf
